plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1'
    id 'com.diffplug.spotless' version '8.10.0'
}

group = 'org.maboroshi'
def baseVersion = '1.7.0'

def getGitHash = { ->
    if (System.getenv("GITHUB_SHA") != null) {
        return System.getenv("GITHUB_SHA").take(6)
    }
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short=6'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    } catch (Exception ignored) {
        return "alpha"
    }
}

version = project.hasProperty('release') && project.property('release') == 'true' ?
          baseVersion : "${baseVersion}-${getGitHash()}"

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        url = "https://repo.opencollab.dev/main/"
    }
    maven {
        url = "https://repo.codemc.io/repository/creatorfromhell/"
    }
    maven {
        url = "https://repo.extendedclip.com/releases/"
    }
    maven {
        url = "https://jitpack.io/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")
    compileOnly("de.exlll:configlib-paper:4.8.1")
    implementation("org.bstats:bstats-bukkit:3.2.1")
    compileOnly("org.geysermc.floodgate:api:2.2.5-SNAPSHOT")
    compileOnly("net.milkbowl.vault:VaultUnlockedAPI:2.20")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7.1")
    compileOnly("net.luckperms:api:5.5")
    compileOnly("me.clip:placeholderapi:2.12.3")
}

tasks.register("printVersion") {
    group = "versioning"
    doLast {
        println("VERSION=${version}")
    }
}

tasks.named('shadowJar') {
  relocate 'org.bstats', 'org.maboroshi.junction.libs.bstats'
  exclude 'plugin.yml'
  minimize()
  archiveClassifier.set('')
}

build.dependsOn shadowJar
build.dependsOn spotlessApply

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.add("-parameters")
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('paper-plugin.yml') {
        expand props
    }
}

spotless {
  format 'misc', {
    target '*.gradle', '.gitattributes', '.gitignore'
    trimTrailingWhitespace()
    leadingTabsToSpaces()
    endWithNewline()
  }

  java {
    importOrder()
    removeUnusedImports()
    forbidWildcardImports()
    cleanthat()
    palantirJavaFormat('2.96.0')
    formatAnnotations()
  }
}
