name: Junction
version: "1.0-SNAPSHOT"
main: com.muhdfdeen.junction.Junction
description: Automatically assigns Bedrock Edition players to groups using Floodgate and LuckPerms
author: muhdfdeen
website: https://github.com/muhdfdeen/junction
api-version: "1.21"
dependencies:
  server:
    floodgate:
      load: BEFORE
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
