name: Junction
version: "1.1.0"
main: com.muhdfdeen.junction.Junction
description: A Minecraft plugin that automatically assigns Bedrock Edition players to a permission group using Floodgate.
author: muhdfdeen
website: https://github.com/muhdfdeen/junction
api-version: "1.21"
dependencies:
  server:
    floodgate:
      load: BEFORE
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
